### ISSUE TITLE
Not an issue more a question for add_task arg

### ISSUE THREAD

**Issue by mraniki** [tarsil/asyncz#26]
Thanks for the lib, it does the job but I'm not clear on how I can pass arg/kwarg(f"{await self.trend.fetch_key_feed()}")  to my scheduled fn (self.send_notification).
I created a secondary function for now send_news which work:

I have the following

    async def send_news(self):
        """News"""
        await self.send_notification(f"{await self.trend.fetch_key_feed()}")

    async def plugin_schedule_task(self):
        """Handles task scheduling"""

        self.scheduler.add_task(
            fn=self.send_news,
            trigger=IntervalTrigger(minutes=2),
            max_instances=1,
            replace_existing=True,
            coalesce=True,
            is_enabled=True
        )

thanks for your guidance @tarsil

**Comment by mraniki** [comment]
Ok so I think I might I found the way: 

    async def plugin_schedule_task(self):
        feed_data = await self.trend.fetch_key_feed()
        self.scheduler.add_task(
            fn=self.send_notification,
            args=[feed_data],
            trigger=IntervalTrigger(minutes=5),
            max_instances=1,
            replace_existing=True,
            coalesce=True,
            is_enabled=True
            )

**Comment by tarsil** [comment]
Hey @mraniki thank you for your question. Seeing both comments, the second option seems indeed the correct way or approaching and the reason for it it's because the fn receives a sync function. 

This is actually something to be considered as a possible feature. Adding the async task as a possibility for the fn parameters. 

What do you think? Are you willing to create a PR or propose that change?

**Comment by tarsil** [comment]
Oh wait, @mraniki i was mistaken with something else. Ignore my comment. The second option you did looks correct to me

**Comment by mraniki** [comment]
It will be good to add it in the doc as an example 👍

**Comment by mraniki** [comment]
> Oh wait, @mraniki i was mistaken with something else. Ignore my comment. The second option you did looks correct to me 

Thanks for the confirmation 👌

**Comment by tarsil** [comment]
> It will be good to add it in the doc as an example 👍 

Are you willing to open a PR and add that? :) You can be a contributor

**Comment by mraniki** [comment]
Sure I will prep that and send it

**Comment by tarsil** [comment]
@mraniki merged. Thank you very much. It should be live in the next 5 minutes. I hope Asyncz is doing well for you
