### ISSUE TITLE
Link on top right bring to 404

### ISSUE THREAD

**Issue by mraniki** [tarsil/asyncz#28]
<img width="349" alt="Screenshot 2023-07-24 at 07 39 28" src="https://github.com/tarsil/asyncz/assets/8766259/b75fff6a-5f82-4ec0-b263-392d1cebe5bc">

top right of the repo the link is broken and should go to https://asyncz.tarsild.io

**Comment by tarsil** [comment]
Nice catch 💪. Somehow that typo escaped me. Fixed now.
